### ISSUE TITLE
SPARQL endpoint

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/semanticoctopus#7]
https://www.w3.org/TR/2013/REC-sparql11-protocol-20130321/

**Comment by cristianolongo** [comment]
Create a server to provide a sparql endpoint by wrapping an aggregation engine.

**Comment by cristianolongo** [comment]
this is a good tutorial for Jetty http://www.codeproject.com/Articles/128145/Run-Jetty-Web-Server-Within-Your-Application#create_jetty_server_instance

**Comment by ool73** [comment]
- Deleted test scope from a pom dependency
- Organized imports
- Added log in query executor

**Comment by ool73** [comment]
Added exception log
